---
deployment:
      tasks:
        - export DEPLOYPATH=/home/deenassa/repo/diantha-test # Add /<app_folder> if required
        - /bin/cp * $DEPLOYPATH                           #copy all from root 